BASE=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:905508f17491d092ce5c81283cac740bb7616d2dcf1947c883849a3a76cf9c4f
KBC_IMG=quay.io/trusted-execution-clusters/trustee-attester:centos-stream-without-tpm-v0.17.0
CLEVIS_PIN_IMG=quay.io/trusted-execution-clusters/clevis-pin-trustee:centos-stream-75015a5
IGNITION_IMG=quay.io/trusted-execution-clusters/ignition:centos-stream-5a45ee84
VERSION=9.6
STREAM=tec
ID=rhel
NAME=rhcos
DESCRIPTION=Red Hat Enterprise Linux CoreOS 9 6 for trusted execution cluster
